version: '2'

services:

  web:
    container_name: 'aspnetCoreApi'
    image: 'proto:aspnetCoreApi'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
     - "5000:5000"
    depends_on:
     - "postgres"
    networks:
      - aspnetcoreapp-network

  postgres:
    container_name: 'postgres'
    image: postgres
    volumes:
      - /opt/db/sc??:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge